### PR TITLE
Feature/branding and theme (better hero icon and CTA's) 

### PR DESCRIPTION
**Pull request by albert118**
## Renders

image

### CODE REVIEW

**Comment by Ryan-Cleminson** [comment]
I like the design but seems there is an issue with the view of it from a laptop (Which most people will actually be viewing it from) :) .

Screenshot 2023-05-04 at 11 05 07 am
Screenshot 2023-05-04 at 11 05 13 am

**Comment by albert118** [comment]
## fixed up to be more responsive

image

image

image

**Comment by Ryan-Cleminson** [comment]
@albert118 LGTM
Screenshot 2023-05-07 at 1 31 48 pm
Screenshot 2023-05-07 at 1 31 57 pm

**Review by Ryan-Cleminson — APPROVED** [review]
LGTM

**Pull request merged**
